"""empty message

Revision ID: 983bb71c8672
Revises: 285ed225370d
Create Date: 2023-01-05 16:14:18.312892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983bb71c8672'
down_revision = '285ed225370d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=50),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
