"""empty message

Revision ID: d5d66ce96395
Revises: ec5f5b42e01a
Create Date: 2023-01-05 17:45:45.469507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d66ce96395'
down_revision = 'ec5f5b42e01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
